version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 25
    assignees:
      - "JorisAerts"
    schedule:
      interval: 'weekly'
      time: '00:00'
      day: 'monday'

    groups:
      eslint:
        patterns:
          - 'eslint*'
          - '@eslint/*'
          - '@typescript-eslint/*'
          - '@rushstack/eslint-patch'
          - '@types/eslint'
      lit:
        patterns:
          - 'lit*'
          - '@lit/*'
      vite:
        patterns:
          - 'vite*'
          - '@vitejs/*'
